#!/usr/bin/env bash
# machine.lua + yt-x config templating: per-host app choices come from
# .chezmoidata/hosts.toml, a host with none of the optional keys gets neutral
# defaults, and the guest profile carries nothing personal. Uses a temp chezmoi
# config so it never touches the real ~/.config/chezmoi/chezmoi.toml.
set -u

repo="$(cd "$(dirname "$0")/.." && pwd)"
fail=0
ok()  { printf '  ok   %s\n' "$1"; }
bad() { printf '  FAIL %s\n' "$1"; fail=1; }

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

render() { # render <tmpl-relpath> <profile> <host>
	cat > "$tmp/chezmoi.toml" <<-EOF
	sourceDir = "$repo"
	[data]
	    profile = "$2"
	    host = "$3"
	EOF
	chezmoi execute-template -f "$repo/$1" --config "$tmp/chezmoi.toml" 2>&1
}

# --- a fully configured host ---------------------------------------------
out=$(render dot_config/hypr/machine.lua.tmpl personal desktop)
if printf '%s' "$out" | grep -q 'file_manager = "dolphin"' \
	&& printf '%s' "$out" | grep -q 'primary_monitor = "DP-1"' \
	&& printf '%s' "$out" | grep -q '"blueman-applet"'; then
	ok "machine.lua carries the host's apps, primary monitor and autostart"
else
	bad "machine.lua for desktop is missing app/autostart data: $out"
fi

# --- a host with none of the optional keys -> neutral defaults -------------
out=$(render dot_config/hypr/machine.lua.tmpl guest pentest)
if printf '%s' "$out" | grep -q 'terminal = "kitty"' \
	&& printf '%s' "$out" | grep -q 'xdg-open' \
	&& printf '%s' "$out" | grep -q 'xdg-settings get default-web-browser' \
	&& printf '%s' "$out" | grep -q 'primary_monitor = ""' \
	&& ! printf '%s' "$out" | grep -qE 'dolphin|"zen"|kdeconnect'; then
	ok "host without optional keys renders neutral defaults (no personal apps)"
else
	bad "defaults for an unconfigured host are wrong: $out"
fi

# --- rendered Lua parses ---------------------------------------------------
if command -v luajit >/dev/null 2>&1; then
	render dot_config/hypr/machine.lua.tmpl personal desktop > "$tmp/m.lua"
	if luajit -bl "$tmp/m.lua" >/dev/null 2>&1 && luajit -bl "$repo/dot_config/hypr/hyprland.lua" >/dev/null 2>&1; then
		ok "machine.lua and hyprland.lua are valid Lua"
	else
		bad "machine.lua or hyprland.lua does not parse as Lua"
	fi
else
	printf '  skip lua syntax check (luajit not installed)\n'
fi

# --- hyprland.lua survives a stale / missing machine.lua ------------------
# Regression: a machine.lua generated by an older version of this repo has no
# terminal/file_manager/browser keys; hyprland.lua must fall back to defaults
# instead of handing nil to exec_cmd ("expected string, got nil").
if command -v luajit >/dev/null 2>&1; then
	mkdir -p "$tmp/home/.config/hypr"
	stub='local proxy; proxy = setmetatable({}, {__index=function() return proxy end, __call=function() return proxy end})
	hl = setmetatable({}, {__index=function(_, k)
	  if k=="dsp" then return setmetatable({}, {__index=function(_, n)
	    if n=="exec_cmd" then return function(a) assert(type(a)=="string", "exec_cmd got "..type(a)); return proxy end end
	    return proxy end}) end
	  return proxy end})'
	for variant in stale absent; do
		rm -f "$tmp/home/.config/hypr/machine.lua"
		[ "$variant" = stale ] && printf 'return { kb_layout = "us", scale = 1, monitors = {}, gpu_env = {} }\n' > "$tmp/home/.config/hypr/machine.lua"
		if HOME="$tmp/home" luajit -e "$stub; dofile('$repo/dot_config/hypr/hyprland.lua')" >"$tmp/lua.out" 2>&1; then
			ok "hyprland.lua loads with a $variant machine.lua (defaults fill the gaps)"
		else
			bad "hyprland.lua breaks with a $variant machine.lua: $(head -c 300 "$tmp/lua.out")"
		fi
	done
fi

# --- yt-x: Zen cookie profile is personal-only ---------------------------
out=$(render dot_config/yt-x/config.tmpl guest desktop)
if printf '%s' "$out" | grep -q '^CONFIG_BROWSER=""' && ! printf '%s' "$out" | grep -q 'zen'; then
	ok "yt-x config: guest gets no Zen cookie profile"
else
	bad "yt-x config leaks the Zen setup to guests: $out"
fi
out=$(render dot_config/yt-x/config.tmpl personal desktop)
if printf '%s' "$out" | grep -q '^CONFIG_BROWSER="firefox:.*yt-x-zen-profile"'; then
	ok "yt-x config: personal keeps the Zen cookie profile"
else
	bad "yt-x config lost the Zen setup for personal: $out"
fi

exit $fail
