add_newline = true

format = """
┌─ $username@$hostname $directory $git_branch $git_status
└─ $character
"""

[username]
show_always = true
style_user = "bold green"

[hostname]
ssh_only = false
style = "bold cyan"

[directory]
style = "blue"
truncation_length = 3

[git_branch]
symbol = " "
style = "purple"

[git_status]
style = "red"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
